# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive')], default='I', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('L', 'Legal'), ('C', 'Compensation'), ('R', 'Recuperation'), ('X', 'Exceptional')], default='L', max_length=1)),
                ('amount_of_days', models.IntegerField()),
                ('first_day', models.DateTimeField()),
                ('last_day', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DemandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Refused'), ('P', 'Pending')], default='P', max_length=1)),
                ('motivation', models.CharField(blank=True, max_length=255, null=True)),
                ('encoding_date', models.DateTimeField(default=models.DateTimeField(default=django.utils.timezone.now))),
                ('encoding_user', models.CharField(max_length=255)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.Demand')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('V', 'Validate demand'), ('A', 'Activate User')], default='V', max_length=1)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.Demand')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('L', 'Legal'), ('C', 'Compensation'), ('R', 'Recuperation'), ('X', 'Exceptional')], default='L', max_length=1)),
                ('amount_of_days', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.Person')),
            ],
        ),
        migrations.AddField(
            model_name='demandstatus',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.Person'),
        ),
        migrations.AddField(
            model_name='demand',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.Person'),
        ),
        migrations.AddField(
            model_name='accountstatus',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacation.Person'),
        ),
    ]
